image: docker:19.03.15

services:
  - docker:19.03.15-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
  - check_docker

check_docker:
  stage: check_docker
  script:
    - docker info
