image: continuumio/miniconda3:latest

stages:
  - build
  - test
  - push

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:latest

build:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker build -t -t $IMAGE_NAME .
  artifacts:
    paths:
      - Dockerfile

test:
  stage: test
  script:
    - docker run $IMAGE_NAME /bin/bash -c "conda run -n reflow pytest -v test.py"


push:
  stage: push
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $IMAGE_NAME
  only:
    - master