channels:
  - conda-forge
  - pvlib
dependencies:
  - python
  - pytest
  - pytest-cov
  - pylint
  - papermill
  - autopep8
  - jupyter
  - notebook
  - pip
  - matplotlib
  - descartes
  - pandas
  - openpyxl
  - numpy<1.22
  - numba
  - scipy
  - scikit-learn
  - gdal=3.4.2
  - netCDF4>=1.5.3
  - xarray
  - pvlib=0.9.0
  - smopy
  - pip:
    - luigi