channels:
  - conda-forge
  - pvlib
dependencies:
  - python=3.10
  - gdal=3.4.2
  - netCDF4>=1.5.3
  - numpy<1.22.*
  - pandas=2.0
  - scipy>1.10.*
  - scikit-learn=1.2.2
  - pvlib=0.9.0
  - pytest
  - pytest-cov
  - pylint
  - papermill
  - autopep8
  - jupyter
  - jupyterlab
  - notebook
  - pip
  - matplotlib
  - descartes
  - openpyxl
  - numba
  - xarray
  - smopy
  - pip:
    - luigi