version: '3'
services:
  reflow:
    build:
      context: .
      dockerfile: Dockerfile
  shapefilegenerator:
    build:
      context: ${SHAPEFILE_GEN_PATH}
      dockerfile: Dockerfile
  reanalysis_downloader:
    build:
      context: $(REANALYSIS_DOWNLOADER_PATH)
      dockerfile: Dockerfile